
OPENAI_API_TYPE="OPENAI_API_TYPE"
OPENAI_DEPLOYMENT_NAME="OPENAI_DEPLOYMENT_NAME"
OPENAI_MODEL="OPENAI_MODEL"
OPENAI_API_VERSION="OPENAI_API_VERSION"
OPENAI_API_BASE="OPENAI_API_BASE"
OPENAI_API_KEY="OPENAI_API_KEY"

# error
ERROR_OK = 0
ERROR_UNKNOW = 5000
ERROR_MILVUS_UNKNOWN = 5101
ERROR_MILVUS_CONNECT_FAILED = 5102

# error string
ERRSTR_MILVUS_CONNECT_FAILED = "Failed to connect Milvus database"
