KnowledgeGraph:
  enabled: true
  servers:
  - server: pole-kg
    address: biocypher
    port: 7687

VectorStore:
  enabled: true
  servers:
  - server: local
    address: standalone
    port: 19530
    


