KnowledgeGraph:
  enabled: true
  servers:
  - server: pole-kg
    address: 10.95.224.94
    port: 7689
    number_of_results: 5
  - server: genomicKB-kg
    address: 10.95.224.94
    port: 47689
    number_of_results: 5

VectorStore:
  enabled: true
  servers:
  - server: local
    address: 10.95.224.94
    port: 19530
    


